---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build DEB
  commands:
  - cd debian
  - ./build-deb-projman.sh

- name: build RPM
  commands:
  - cd ../redhat
  - ./build-rpm.sh
  
trigger:
  event:
    include:
    - push
    
