name: Projman build the packages
run-name: ${{ gitea.actor }} build projman packages
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: tcl-tk-builder:docker://svk28/tcltk-build-debian:latest
    steps:
      - run: cd debian
      - run: ./build-deb-projman.sh
