name: Projman build the packages
run-name: ${{ gitea.actor }} build projman packages
on: [push]
jobs:
  Projman-Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: cd debian
      - run: ./build-deb-projman.sh
