name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Explore-Gitea-Actions:
    runs-on: tcl-tk-builder
    steps:
      - name: Build the packages
        run: |
          git clone ${{ vars.main_url }}${{ gitea.repository }}
          pwd
          cd projman/debian
          ./build-deb-projman.sh
          cd ../../
          curl --user ${{ vars.user}}:${{vars.api_token}} --upload-file "$(ls -1| grep projman | grep -E 'deb$')" ${{vars.main_url}}api/packages/${{vars.user}}/debian/pool/bookworm/main/upload
      - run: echo "This job's status is ${{ job.status }}."
